# Generated by Django 6.0.1 on 2026-01-09 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmacias', '0002_notificacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=200, verbose_name='razão social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=200, verbose_name='nome fantasia')),
                ('nuit', models.CharField(blank=True, max_length=20, verbose_name='NUIT')),
                ('responsavel', models.CharField(blank=True, max_length=100, verbose_name='pessoa de contato')),
                ('telefone_principal', models.CharField(max_length=20, verbose_name='telefone')),
                ('telefone_secundario', models.CharField(blank=True, max_length=20, verbose_name='telefone secundário')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('website', models.URLField(blank=True)),
                ('endereco', models.TextField(blank=True, verbose_name='endereço')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='cidade')),
                ('prazo_pagamento_dias', models.PositiveIntegerField(default=30, help_text='Dias para pagamento após a fatura', verbose_name='prazo padrão (dias)')),
                ('limite_kredito', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='limite de crédito')),
                ('banco', models.CharField(blank=True, max_length=100, verbose_name='banco')),
                ('conta_bancaria', models.CharField(blank=True, max_length=50, verbose_name='nº da conta')),
                ('iban', models.CharField(blank=True, max_length=50, verbose_name='IBAN')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('is_ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('farmacia', models.ForeignKey(help_text='Farmácia que cadastrou este fornecedor', on_delete=django.db.models.deletion.CASCADE, related_name='meus_fornecedores', to='farmacias.farmacia', verbose_name='farmácia')),
            ],
            options={
                'verbose_name': 'fornecedor',
                'verbose_name_plural': 'fornecedores',
                'ordering': ['nome_fantasia', 'razao_social'],
            },
        ),
    ]
