# Generated by Django 5.2.10 on 2026-01-13 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foto_documento',
            field=models.ImageField(blank=True, null=True, upload_to='documentos/', verbose_name='foto do documento'),
        ),
    ]
