# Generated by Django 6.0.1 on 2026-01-08 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('nome_fantasia', models.CharField(blank=True, max_length=200, verbose_name='nome fantasia')),
                ('nuit', models.CharField(max_length=20, unique=True, verbose_name='NUIT')),
                ('alvara', models.CharField(blank=True, max_length=100, verbose_name='alvará')),
                ('telefone_principal', models.CharField(max_length=20, verbose_name='telefone principal')),
                ('telefone_alternativo', models.CharField(blank=True, max_length=20, verbose_name='telefone alternativo')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('endereco', models.TextField(verbose_name='endereço')),
                ('bairro', models.CharField(max_length=100, verbose_name='bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='cidade')),
                ('provincia', models.CharField(max_length=100, verbose_name='província')),
                ('codigo_postal', models.CharField(blank=True, max_length=20, verbose_name='código postal')),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude para localização no mapa', max_digits=9, verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude para localização no mapa', max_digits=9, verbose_name='longitude')),
                ('horario_abertura', models.TimeField(blank=True, null=True, verbose_name='horário de abertura')),
                ('horario_fechamento', models.TimeField(blank=True, null=True, verbose_name='horário de fechamento')),
                ('funciona_24h', models.BooleanField(default=False, verbose_name='funciona 24h')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='farmacias/logos/', verbose_name='logo')),
                ('foto_fachada', models.ImageField(blank=True, null=True, upload_to='farmacias/fotos/', verbose_name='foto da fachada')),
                ('is_ativa', models.BooleanField(default=True, verbose_name='ativa')),
                ('is_verificada', models.BooleanField(default=False, verbose_name='verificada')),
                ('aceita_entregas', models.BooleanField(default=True, verbose_name='aceita entregas')),
                ('raio_entrega_km', models.DecimalField(decimal_places=2, default=5.0, help_text='Raio máximo de entrega em quilômetros', max_digits=5, verbose_name='raio de entrega (km)')),
                ('taxa_entrega', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='taxa de entrega')),
                ('nota_media', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='nota média')),
                ('total_avaliacoes', models.PositiveIntegerField(default=0, verbose_name='total de avaliações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='data de atualização')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmacia', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'farmácia',
                'verbose_name_plural': 'farmácias',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoFarmacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Nota de 1 a 5', verbose_name='nota')),
                ('comentario', models.TextField(blank=True, verbose_name='comentário')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_farmacias', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='farmacias.farmacia', verbose_name='farmácia')),
            ],
            options={
                'verbose_name': 'avaliação de farmácia',
                'verbose_name_plural': 'avaliações de farmácias',
                'ordering': ['-data_criacao'],
                'unique_together': {('farmacia', 'usuario')},
            },
        ),
    ]
