# Generated by Django 6.0.1 on 2026-01-09 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VALIDADE', 'Validade Próxima'), ('EXPIRADO', 'Produto Expirado'), ('ESTOQUE', 'Estoque Baixo'), ('PEDIDO', 'Novo Pedido'), ('SISTEMA', 'Sistema')], default='SISTEMA', max_length=20, verbose_name='tipo')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('mensagem', models.TextField(verbose_name='mensagem')),
                ('lida', models.BooleanField(default=False, verbose_name='lida')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='farmacias.farmacia', verbose_name='farmácia')),
            ],
            options={
                'verbose_name': 'notificação',
                'verbose_name_plural': 'notificações',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
