# Generated by Django 5.2.10 on 2026-01-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacias', '0002_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmacia',
            name='banco_conta',
            field=models.CharField(blank=True, max_length=50, verbose_name='número da conta'),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='banco_nib',
            field=models.CharField(blank=True, max_length=50, verbose_name='NIB'),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='banco_nome',
            field=models.CharField(blank=True, max_length=100, verbose_name='nome do banco'),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='emola_numero',
            field=models.CharField(blank=True, max_length=20, verbose_name='número e-Mola'),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='mpesa_numero',
            field=models.CharField(blank=True, max_length=20, verbose_name='número M-Pesa'),
        ),
    ]
