# Generated by Django 5.2.10 on 2026-01-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacias', '0003_farmacia_banco_conta_farmacia_banco_nib_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmacia',
            name='percentual_iva',
            field=models.DecimalField(decimal_places=2, default=16.0, max_digits=5, verbose_name='Taxa IVA (%)'),
        ),
    ]
