# Generated by Django 5.2.10 on 2026-01-29 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacias', '0004_farmacia_percentual_iva'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmacia',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmacia_perfil', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
    ]
