# Generated by Django 5.2.10 on 2026-01-29 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacias', '0005_alter_farmacia_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gibagio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='código')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('is_ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='farmacia',
            name='gibagio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmacias', to='farmacias.gibagio', verbose_name='Gibagio / Gestão Local'),
        ),
        migrations.CreateModel(
            name='Licenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MENSAL', 'Mensal'), ('ANUAL', 'Anual'), ('TRIAL', 'Teste (7 dias)')], default='TRIAL', max_length=20)),
                ('chave', models.CharField(blank=True, max_length=100, unique=True, verbose_name='chave da licença')),
                ('data_inicio', models.DateField(verbose_name='data de início')),
                ('data_fim', models.DateField(verbose_name='data de término')),
                ('is_ativa', models.BooleanField(default=True, verbose_name='ativa')),
                ('paga', models.BooleanField(default=False, verbose_name='paga')),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licencas', to='farmacias.farmacia')),
            ],
        ),
    ]
