# Generated by Django 5.2.10 on 2026-01-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacias', '0006_gibagio_farmacia_gibagio_licenca'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmacia',
            name='meta_bonus_mensal',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Volume de vendas necessário para desbloquear bónus extra da equipa', max_digits=12, verbose_name='meta de bónus mensal'),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='percentual_bonus_extra',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Percentual extra pago se a meta for atingida', max_digits=5, verbose_name='bónus extra (%)'),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='percentual_comissao_padrao',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Percentual aplicado se o produto não tiver uma comissão específica', max_digits=5, verbose_name='comissão padrão (%)'),
        ),
    ]
