# Generated by Django 6.0.1 on 2026-01-09 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmacias', '0002_notificacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome completo')),
                ('apelido', models.CharField(blank=True, max_length=100, verbose_name='apelido')),
                ('nuit', models.CharField(blank=True, max_length=20, verbose_name='NUIT/BI')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('telefone', models.CharField(max_length=20, verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('endereco', models.TextField(blank=True, verbose_name='endereço')),
                ('alergias', models.TextField(blank=True, verbose_name='alergias conhecidas')),
                ('doencas_cronicas', models.TextField(blank=True, help_text='Ex: Diabetes, Hipertensão', verbose_name='doenças crônicas')),
                ('limite_fiado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='limite de crédito/fiado')),
                ('saldo_devedor', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='saldo devedor atual')),
                ('is_bloqueado', models.BooleanField(default=False, help_text='Bloquear compras a prazo', verbose_name='bloqueado')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('ultima_compra', models.DateTimeField(blank=True, null=True, verbose_name='última compra')),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meus_clientes', to='farmacias.farmacia', verbose_name='farmácia')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['nome'],
            },
        ),
    ]
