# Generated by Django 5.2.10 on 2026-01-25 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('farmacias', '0003_farmacia_banco_conta_farmacia_banco_nib_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['-data_cadastro'], 'verbose_name': 'cliente', 'verbose_name_plural': 'clientes'},
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nome',
            new_name='nome_completo',
        ),
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together={('farmacia', 'telefone')},
        ),
        migrations.AddField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, verbose_name='bairro'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(blank=True, default='Maputo', max_length=100, verbose_name='cidade'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='data de atualização'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='is_ativo',
            field=models.BooleanField(default=True, verbose_name='ativo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('COMUM', 'Comum'), ('CADASTRADO', 'Cadastrado'), ('ONLINE', 'Online')], default='COMUM', max_length=20, verbose_name='tipo de cliente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.OneToOneField(blank=True, help_text='Vinculado apenas se for cliente online', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente_perfil', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data de cadastro'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(blank=True, max_length=300, verbose_name='endereço'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='farmacia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='farmacias.farmacia', verbose_name='farmácia'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nuit',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='NUIT'),
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='alergias',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='apelido',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='doencas_cronicas',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='is_bloqueado',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='limite_fiado',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='saldo_devedor',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='ultima_compra',
        ),
    ]
