# Generated by Django 5.2.10 on 2026-02-22 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_options_and_more'),
        ('pedidos', '0007_pedido_sessao_caixa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='is_bloqueado',
            field=models.BooleanField(default=False, verbose_name='bloqueado para crédito'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='limite_credito',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='limite de crédito'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='saldo_atual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='saldo atual (Dívida)'),
        ),
        migrations.CreateModel(
            name='MovimentoContaCorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DEBITO', 'Débito (Venda a Prazo)'), ('CREDITO', 'Crédito (Pagamento/Recebimento)'), ('AJUSTE', 'Ajuste de Saldo')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_movimento', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.CharField(max_length=255)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('is_liquidado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos_cc', to='clientes.cliente')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.pedido')),
                ('realizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'movimento de conta corrente',
                'verbose_name_plural': 'movimentos de conta corrente',
                'ordering': ['-data_movimento'],
            },
        ),
    ]
