# Generated by Django 6.0.1 on 2026-01-08 16:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmacias', '0001_initial'),
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(editable=False, max_length=50, unique=True, verbose_name='número do pedido')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADO', 'Confirmado'), ('PREPARANDO', 'Preparando'), ('PRONTO', 'Pronto para Entrega'), ('EM_TRANSITO', 'Em Trânsito'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='status')),
                ('forma_pagamento', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('CARTAO', 'Cartão'), ('MPESA', 'M-Pesa'), ('TRANSFERENCIA', 'Transferência'), ('ONLINE', 'Pagamento Online')], default='DINHEIRO', max_length=20, verbose_name='forma de pagamento')),
                ('pago', models.BooleanField(default=False, verbose_name='pago')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='subtotal')),
                ('taxa_entrega', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='taxa de entrega')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='desconto')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total')),
                ('endereco_entrega', models.TextField(verbose_name='endereço de entrega')),
                ('bairro', models.CharField(max_length=100, verbose_name='bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='cidade')),
                ('referencia', models.TextField(blank=True, verbose_name='ponto de referência')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('telefone_contato', models.CharField(max_length=20, verbose_name='telefone de contato')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('observacoes_farmacia', models.TextField(blank=True, verbose_name='observações da farmácia')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='pedidos/qrcodes/', verbose_name='QR Code')),
                ('codigo_validacao', models.CharField(blank=True, max_length=50, verbose_name='código de validação')),
                ('validado', models.BooleanField(default=False, verbose_name='validado')),
                ('data_validacao', models.DateTimeField(blank=True, null=True, verbose_name='data de validação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('data_confirmacao', models.DateTimeField(blank=True, null=True, verbose_name='data de confirmação')),
                ('data_entrega_prevista', models.DateTimeField(blank=True, null=True, verbose_name='data de entrega prevista')),
                ('data_entrega', models.DateTimeField(blank=True, null=True, verbose_name='data de entrega')),
                ('data_cancelamento', models.DateTimeField(blank=True, null=True, verbose_name='data de cancelamento')),
                ('motivo_cancelamento', models.TextField(blank=True, verbose_name='motivo de cancelamento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL, verbose_name='cliente')),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='farmacias.farmacia', verbose_name='farmácia')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço unitário')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='subtotal')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('estoque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_pedido', to='produtos.estoqueproduto', verbose_name='estoque')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_pedido', to='produtos.produto', verbose_name='produto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedidos.pedido', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'item do pedido',
                'verbose_name_plural': 'itens do pedido',
            },
        ),
        migrations.CreateModel(
            name='HistoricoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(blank=True, max_length=20, verbose_name='status anterior')),
                ('status_novo', models.CharField(max_length=20, verbose_name='status novo')),
                ('observacao', models.TextField(blank=True, verbose_name='observação')),
                ('data_mudanca', models.DateTimeField(auto_now_add=True, verbose_name='data da mudança')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mudancas_pedido', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='pedidos.pedido', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'histórico do pedido',
                'verbose_name_plural': 'históricos dos pedidos',
                'ordering': ['-data_mudanca'],
            },
        ),
    ]
