# Generated by Django 6.0.1 on 2026-01-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='codigo_validacao',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='uuid',
        ),
        migrations.AddField(
            model_name='pedido',
            name='codigo_coleta',
            field=models.CharField(blank=True, max_length=6, verbose_name='código de coleta'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='codigo_entrega',
            field=models.CharField(blank=True, max_length=6, verbose_name='código de entrega'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='coletado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='qrcode_coleta',
            field=models.ImageField(blank=True, null=True, upload_to='pedidos/qrcodes/coleta/', verbose_name='QR Coleta'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='qrcode_entrega',
            field=models.ImageField(blank=True, null=True, upload_to='pedidos/qrcodes/entrega/', verbose_name='QR Entrega'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, verbose_name='bairro'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cidade',
            field=models.CharField(default='Maputo', max_length=100, verbose_name='cidade'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_validacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data da validação'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='endereco_entrega',
            field=models.CharField(blank=True, max_length=255, verbose_name='endereço de entrega'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.CharField(choices=[('DINHEIRO', 'Dinheiro (Cash)'), ('POS', 'POS / Cartão na Entrega'), ('MPESA', 'M-Pesa'), ('EMOLA', 'e-Mola'), ('VISA_ONLINE', 'Visa/Mastercard Online'), ('TRANSFERENCIA', 'Transferência Bancária')], max_length=20, verbose_name='forma de pagamento'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero_pedido',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='número do pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='referencia',
            field=models.CharField(blank=True, max_length=255, verbose_name='ponto de referência'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='subtotal'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='telefone_contato',
            field=models.CharField(blank=True, max_length=20, verbose_name='telefone de contato'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='total'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='validado',
            field=models.BooleanField(default=False, verbose_name='entrega validada'),
        ),
    ]
