# Generated by Django 6.0.1 on 2026-01-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_remove_pedido_codigo_validacao_remove_pedido_qr_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='qrcode_fatura',
            field=models.ImageField(blank=True, null=True, upload_to='pedidos/qrcodes/fatura/', verbose_name='QR Fatura'),
        ),
    ]
