# Generated by Django 5.2.10 on 2026-01-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_pedido_entregador'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='receita_medica',
            field=models.ImageField(blank=True, help_text='Upload da receita médica (foto ou scan)', null=True, upload_to='receitas/%Y/%m/', verbose_name='receita médica'),
        ),
    ]
