# Generated by Django 5.2.10 on 2026-01-29 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_pedido_receita_medica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='is_avulso',
            field=models.BooleanField(default=False, verbose_name='venda avulsa'),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='valor_comissao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor comissão'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='troco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='troco'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='valor pago'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='vendedor'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.CharField(choices=[('DINHEIRO', 'Dinheiro (Cash)'), ('POS', 'POS / Cartão na Entrega'), ('MPESA', 'M-Pesa'), ('EMOLA', 'e-Mola'), ('VISA_ONLINE', 'Visa/Mastercard Online'), ('TRANSFERENCIA', 'Transferência Bancária'), ('CREDITO', 'Crédito / Conta Corrente')], max_length=20, verbose_name='forma de pagamento'),
        ),
    ]
