# Generated by Django 5.2.10 on 2026-02-22 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0001_initial'),
        ('pedidos', '0006_itempedido_is_avulso_itempedido_valor_comissao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='sessao_caixa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas', to='caixa.sessaocaixa', verbose_name='sessão de caixa'),
        ),
    ]
