# Generated by Django 5.2.10 on 2026-01-12 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entregas', '0002_motoboycliente'),
        ('farmacias', '0002_notificacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoPrioridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('FARMACIA', 'Farmácia'), ('MOTOBOY', 'Motoboy')], max_length=20)),
                ('duracao_dias', models.IntegerField(choices=[(7, '7 dias'), (15, '15 dias'), (30, '30 dias'), (90, '90 dias')])),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
                ('ordem_prioridade', models.IntegerField(default=1, help_text='1=Mais alta, 5=Mais baixa')),
            ],
            options={
                'verbose_name': 'Plano de Prioridade',
                'verbose_name_plural': 'Planos de Prioridade',
                'ordering': ['tipo', 'ordem_prioridade'],
            },
        ),
        migrations.CreateModel(
            name='AssinaturaPrioridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente Aprovação'), ('ATIVA', 'Ativa'), ('EXPIRADA', 'Expirada'), ('CANCELADA', 'Cancelada'), ('REJEITADA', 'Rejeitada')], default='PENDENTE', max_length=20)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comprovativo_pagamento', models.ImageField(blank=True, null=True, upload_to='prioridade/comprovantes/')),
                ('observacoes_admin', models.TextField(blank=True)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assinaturas_aprovadas', to=settings.AUTH_USER_MODEL)),
                ('farmacia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas_prioridade', to='farmacias.farmacia')),
                ('motoboy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas_prioridade', to='entregas.entregador')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prioridade.planoprioridade')),
            ],
            options={
                'verbose_name': 'Assinatura de Prioridade',
                'verbose_name_plural': 'Assinaturas de Prioridade',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoPrioridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=100)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('detalhes', models.TextField(blank=True)),
                ('assinatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='prioridade.assinaturaprioridade')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Prioridade',
                'verbose_name_plural': 'Históricos de Prioridade',
                'ordering': ['-data'],
            },
        ),
    ]
