# Generated by Django 5.2.10 on 2026-01-25 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmacias', '0003_farmacia_banco_conta_farmacia_banco_nib_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('farmacia', models.ForeignKey(blank=True, help_text='Se nulo, é uma categoria padrão do sistema', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias_despesa', to='farmacias.farmacia', verbose_name='farmácia')),
            ],
            options={
                'verbose_name': 'categoria de despesa',
                'verbose_name_plural': 'categorias de despesas',
                'ordering': ['nome'],
                'unique_together': {('nome', 'farmacia')},
            },
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ex: Conta de Luz Janeiro', max_length=200, verbose_name='título')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor')),
                ('data_vencimento', models.DateField(verbose_name='data de vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='data de pagamento')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='status')),
                ('metodo_pagamento', models.CharField(blank=True, choices=[('DINHEIRO', 'Dinheiro'), ('TRANSFERENCIA', 'Transferência Bancária'), ('MPESA', 'M-Pesa'), ('EMOLA', 'E-Mola'), ('CARTAO', 'Cartão (POS)'), ('CHEQUE', 'Cheque'), ('OUTRO', 'Outro')], max_length=20, null=True, verbose_name='método de pagamento')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='despesas/comprovantes/', verbose_name='comprovante')),
                ('is_recorrente', models.BooleanField(default=False, help_text='Marque para despesas fixas como Salário, Aluguel', verbose_name='é recorrente (mensal)')),
                ('dia_vencimento_recorrente', models.PositiveSmallIntegerField(blank=True, help_text='Dia do mês para gerar próxima cobrança (1-31)', null=True, verbose_name='dia de vencimento')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despesas', to='financeiro.categoriadespesa', verbose_name='categoria')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas_criadas', to=settings.AUTH_USER_MODEL)),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='farmacias.farmacia', verbose_name='farmácia')),
            ],
            options={
                'verbose_name': 'despesa',
                'verbose_name_plural': 'despesas',
                'ordering': ['-data_vencimento'],
            },
        ),
    ]
