# Generated by Django 6.0.1 on 2026-01-08 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AGUARDANDO', 'Aguardando Entregador'), ('ATRIBUIDA', 'Atribuída'), ('ACEITA', 'Aceita'), ('COLETADA', 'Coletada'), ('EM_TRANSITO', 'Em Trânsito'), ('ENTREGUE', 'Entregue'), ('CANCELADA', 'Cancelada'), ('RECUSADA', 'Recusada')], default='AGUARDANDO', max_length=20, verbose_name='status')),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='distância (km)')),
                ('tempo_estimado_minutos', models.PositiveIntegerField(blank=True, null=True, verbose_name='tempo estimado (minutos)')),
                ('latitude_coleta', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='latitude coleta')),
                ('longitude_coleta', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='longitude coleta')),
                ('latitude_entrega', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='latitude entrega')),
                ('longitude_entrega', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='longitude entrega')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('data_atribuicao', models.DateTimeField(blank=True, null=True, verbose_name='data de atribuição')),
                ('data_aceitacao', models.DateTimeField(blank=True, null=True, verbose_name='data de aceitação')),
                ('data_coleta', models.DateTimeField(blank=True, null=True, verbose_name='data de coleta')),
                ('data_inicio_transito', models.DateTimeField(blank=True, null=True, verbose_name='data início trânsito')),
                ('data_entrega', models.DateTimeField(blank=True, null=True, verbose_name='data de entrega')),
                ('data_cancelamento', models.DateTimeField(blank=True, null=True, verbose_name='data de cancelamento')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('motivo_cancelamento', models.TextField(blank=True, verbose_name='motivo de cancelamento')),
                ('motivo_recusa', models.TextField(blank=True, verbose_name='motivo de recusa')),
                ('codigo_validacao_coleta', models.CharField(blank=True, max_length=50, verbose_name='código validação coleta')),
                ('codigo_validacao_entrega', models.CharField(blank=True, max_length=50, verbose_name='código validação entrega')),
                ('validado_coleta', models.BooleanField(default=False, verbose_name='validado coleta')),
                ('validado_entrega', models.BooleanField(default=False, verbose_name='validado entrega')),
                ('foto_comprovante', models.ImageField(blank=True, null=True, upload_to='entregas/comprovantes/', verbose_name='foto comprovante')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrega', to='pedidos.pedido', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'entrega',
                'verbose_name_plural': 'entregas',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Nota de 1 a 5', verbose_name='nota')),
                ('comentario', models.TextField(blank=True, verbose_name='comentário')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('entrega', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao', to='entregas.entrega', verbose_name='entrega')),
            ],
            options={
                'verbose_name': 'avaliação de entrega',
                'verbose_name_plural': 'avaliações de entregas',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Entregador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_identidade', models.CharField(max_length=50, unique=True, verbose_name='documento de identidade')),
                ('data_nascimento', models.DateField(verbose_name='data de nascimento')),
                ('foto_documento', models.ImageField(blank=True, null=True, upload_to='entregadores/documentos/', verbose_name='foto do documento')),
                ('tipo_veiculo', models.CharField(choices=[('MOTO', 'Moto'), ('BICICLETA', 'Bicicleta'), ('CARRO', 'Carro'), ('A_PE', 'A pé')], default='MOTO', max_length=50, verbose_name='tipo de veículo')),
                ('placa_veiculo', models.CharField(blank=True, max_length=20, verbose_name='placa do veículo')),
                ('modelo_veiculo', models.CharField(blank=True, max_length=100, verbose_name='modelo do veículo')),
                ('cor_veiculo', models.CharField(blank=True, max_length=50, verbose_name='cor do veículo')),
                ('carta_conducao', models.CharField(blank=True, max_length=50, verbose_name='carta de condução')),
                ('validade_carta', models.DateField(blank=True, null=True, verbose_name='validade da carta')),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('OCUPADO', 'Ocupado'), ('OFFLINE', 'Offline'), ('INATIVO', 'Inativo')], default='OFFLINE', max_length=20, verbose_name='status')),
                ('is_verificado', models.BooleanField(default=False, verbose_name='verificado')),
                ('is_ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('latitude_atual', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude atual')),
                ('longitude_atual', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude atual')),
                ('ultima_localizacao', models.DateTimeField(blank=True, null=True, verbose_name='última localização')),
                ('total_entregas', models.PositiveIntegerField(default=0, verbose_name='total de entregas')),
                ('nota_media', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='nota média')),
                ('total_avaliacoes', models.PositiveIntegerField(default=0, verbose_name='total de avaliações')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='data de cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='data de atualização')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entregador', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'entregador',
                'verbose_name_plural': 'entregadores',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.AddField(
            model_name='entrega',
            name='entregador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas', to='entregas.entregador', verbose_name='entregador'),
        ),
        migrations.CreateModel(
            name='RastreamentoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='longitude')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rastreamentos', to='entregas.entrega', verbose_name='entrega')),
            ],
            options={
                'verbose_name': 'rastreamento de entrega',
                'verbose_name_plural': 'rastreamentos de entregas',
                'ordering': ['-timestamp'],
            },
        ),
    ]
