# Generated by Django 5.2.10 on 2026-01-12 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotoboyCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('placa_moto', models.CharField(blank=True, max_length=10)),
                ('observacoes', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meus_motoboys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Motoboy do Cliente',
                'verbose_name_plural': 'Motoboys dos Clientes',
                'ordering': ['-data_cadastro'],
            },
        ),
    ]
