# Generated by Django 5.2.10 on 2026-01-13 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0002_motoboycliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entregador',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregadores_aprovados', to=settings.AUTH_USER_MODEL, verbose_name='aprovado por'),
        ),
        migrations.AddField(
            model_name='entregador',
            name='data_aprovacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data de aprovação'),
        ),
        migrations.AddField(
            model_name='entregador',
            name='documento_veiculo',
            field=models.ImageField(blank=True, help_text='TVDE, Seguro, etc', null=True, upload_to='entregadores/docs_veiculo/', verbose_name='documento do veículo'),
        ),
        migrations.AddField(
            model_name='entregador',
            name='estado_veiculo',
            field=models.CharField(blank=True, help_text='Ex: Bom, Regular, Novo', max_length=100, verbose_name='estado do veículo'),
        ),
        migrations.AddField(
            model_name='entregador',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='entregadores/perfis/', verbose_name='foto de perfil'),
        ),
        migrations.AddField(
            model_name='entregador',
            name='foto_veiculo',
            field=models.ImageField(blank=True, null=True, upload_to='entregadores/veiculos/', verbose_name='foto do veículo'),
        ),
        migrations.AddField(
            model_name='entregador',
            name='motivo_rejeicao',
            field=models.TextField(blank=True, verbose_name='motivo da rejeição'),
        ),
        migrations.AddField(
            model_name='entregador',
            name='status_aprovacao',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=20, verbose_name='status de aprovação'),
        ),
    ]
