# Generated by Django 6.0.1 on 2026-01-08 16:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_gateway', models.CharField(max_length=200, unique=True, verbose_name='token do gateway')),
                ('ultimos_digitos', models.CharField(max_length=4, verbose_name='últimos 4 dígitos')),
                ('bandeira', models.CharField(choices=[('VISA', 'Visa'), ('MASTERCARD', 'Mastercard'), ('AMEX', 'American Express'), ('DISCOVER', 'Discover'), ('OUTRO', 'Outro')], max_length=20, verbose_name='bandeira')),
                ('nome_titular', models.CharField(max_length=200, verbose_name='nome do titular')),
                ('mes_validade', models.PositiveSmallIntegerField(verbose_name='mês de validade')),
                ('ano_validade', models.PositiveSmallIntegerField(verbose_name='ano de validade')),
                ('is_principal', models.BooleanField(default=False, verbose_name='cartão principal')),
                ('is_ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='data de atualização')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoes', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'cartão de crédito',
                'verbose_name_plural': 'cartões de crédito',
                'ordering': ['-is_principal', '-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('numero_transacao', models.CharField(blank=True, max_length=100, unique=True, verbose_name='número da transação')),
                ('metodo', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('CARTAO_DEBITO', 'Cartão de Débito'), ('MPESA', 'M-Pesa'), ('EMOLA', 'E-Mola'), ('TRANSFERENCIA', 'Transferência Bancária'), ('STRIPE', 'Stripe'), ('PAYPAL', 'PayPal')], max_length=20, verbose_name='método de pagamento')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Processando'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado'), ('CANCELADO', 'Cancelado'), ('REEMBOLSADO', 'Reembolsado'), ('ERRO', 'Erro')], default='PENDENTE', max_length=20, verbose_name='status')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('taxa_processamento', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='taxa de processamento')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor total')),
                ('gateway_transacao_id', models.CharField(blank=True, max_length=200, verbose_name='ID transação gateway')),
                ('gateway_resposta', models.JSONField(blank=True, null=True, verbose_name='resposta do gateway')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('data_processamento', models.DateTimeField(blank=True, null=True, verbose_name='data de processamento')),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True, verbose_name='data de aprovação')),
                ('data_recusa', models.DateTimeField(blank=True, null=True, verbose_name='data de recusa')),
                ('data_cancelamento', models.DateTimeField(blank=True, null=True, verbose_name='data de cancelamento')),
                ('data_reembolso', models.DateTimeField(blank=True, null=True, verbose_name='data de reembolso')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('motivo_recusa', models.TextField(blank=True, verbose_name='motivo de recusa')),
                ('motivo_cancelamento', models.TextField(blank=True, verbose_name='motivo de cancelamento')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='pedidos.pedido', verbose_name='pedido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'pagamento',
                'verbose_name_plural': 'pagamentos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(blank=True, max_length=20, verbose_name='status anterior')),
                ('status_novo', models.CharField(max_length=20, verbose_name='status novo')),
                ('observacao', models.TextField(blank=True, verbose_name='observação')),
                ('data_mudanca', models.DateTimeField(auto_now_add=True, verbose_name='data da mudança')),
                ('pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='pagamentos.pagamento', verbose_name='pagamento')),
            ],
            options={
                'verbose_name': 'histórico de pagamento',
                'verbose_name_plural': 'históricos de pagamentos',
                'ordering': ['-data_mudanca'],
            },
        ),
        migrations.CreateModel(
            name='Reembolso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_solicitado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor solicitado')),
                ('valor_aprovado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valor aprovado')),
                ('status', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('EM_ANALISE', 'Em Análise'), ('APROVADO', 'Aprovado'), ('PROCESSANDO', 'Processando'), ('CONCLUIDO', 'Concluído'), ('RECUSADO', 'Recusado')], default='SOLICITADO', max_length=20, verbose_name='status')),
                ('motivo', models.TextField(verbose_name='motivo')),
                ('resposta', models.TextField(blank=True, verbose_name='resposta')),
                ('gateway_reembolso_id', models.CharField(blank=True, max_length=200, verbose_name='ID reembolso gateway')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='data de solicitação')),
                ('data_analise', models.DateTimeField(blank=True, null=True, verbose_name='data de análise')),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True, verbose_name='data de aprovação')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='data de conclusão')),
                ('data_recusa', models.DateTimeField(blank=True, null=True, verbose_name='data de recusa')),
                ('pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reembolsos', to='pagamentos.pagamento', verbose_name='pagamento')),
            ],
            options={
                'verbose_name': 'reembolso',
                'verbose_name_plural': 'reembolsos',
                'ordering': ['-data_solicitacao'],
            },
        ),
    ]
