# Generated by Django 5.2.10 on 2026-01-25 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmacias', '0003_farmacia_banco_conta_farmacia_banco_nib_and_more'),
        ('financeiro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome completo')),
                ('cargo', models.CharField(choices=[('FARMACEUTICO', 'Farmacêutico'), ('ATENDENTE', 'Atendente de Balcão'), ('CAIXA', 'Operador de Caixa'), ('GERENTE', 'Gerente'), ('ENTREGADOR', 'Entregador'), ('LIMPEZA', 'Auxiliar de Limpeza'), ('GUARDA', 'Guarda/Segurança'), ('OUTRO', 'Outro')], max_length=50, verbose_name='cargo')),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='salário base')),
                ('data_admissao', models.DateField(verbose_name='data de admissão')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('telefone', models.CharField(max_length=20, verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('nuit', models.CharField(blank=True, max_length=20, verbose_name='NUIT')),
                ('endereco', models.TextField(blank=True, verbose_name='endereço')),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='farmacias.farmacia', verbose_name='farmácia')),
                ('usuario', models.OneToOneField(blank=True, help_text='Vincular se o funcionário usa o sistema', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionario_perfil', to=settings.AUTH_USER_MODEL, verbose_name='usuário do sistema')),
            ],
        ),
        migrations.CreateModel(
            name='FolhaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.DateField(help_text='Dia 1 do mês referente', verbose_name='mês de referência')),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='salário base')),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='bônus/comissões')),
                ('descontos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='descontos/faltas')),
                ('total_liquido', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total líquido')),
                ('data_pagamento', models.DateField(verbose_name='data do pagamento')),
                ('pago', models.BooleanField(default=False, verbose_name='pago')),
                ('despesa_vinculada', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folha_origem', to='financeiro.despesa')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='rh.funcionario')),
            ],
        ),
    ]
