# Generated by Django 5.2.10 on 2026-02-22 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmacias', '0007_farmacia_meta_bonus_mensal_and_more'),
        ('financeiro', '0001_initial'),
        ('fornecedores', '0001_initial'),
        ('produtos', '0007_itementrada_tipo_unidade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='código da ordem')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ENVIADA', 'Enviada ao Fornecedor'), ('RECEBIDA_PARCIAL', 'Recebida Parcialmente'), ('CONCLUIDA', 'Concluída (Stock Atualizado)'), ('CANCELADA', 'Cancelada')], default='RASCUNHO', max_length=20)),
                ('data_emissao', models.DateField(auto_now_add=True, verbose_name='data de emissão')),
                ('data_entrega_prevista', models.DateField(blank=True, null=True, verbose_name='entrega prevista')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='valor total')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('comprador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minhas_compras', to=settings.AUTH_USER_MODEL)),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_compra', to='farmacias.farmacia')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_compra', to='fornecedores.fornecedor')),
            ],
            options={
                'verbose_name': 'ordem de compra',
                'verbose_name_plural': 'ordens de compra',
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrdemCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_pedida', models.PositiveIntegerField(verbose_name='qtd pedida')),
                ('quantidade_recebida', models.PositiveIntegerField(default=0, verbose_name='qtd recebida')),
                ('preco_unitario_acordado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='preço unitário')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='desconto (%)')),
                ('preco_ultima_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produto')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='compras.ordemcompra')),
            ],
        ),
        migrations.CreateModel(
            name='FaturaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_fatura', models.CharField(max_length=50, verbose_name='nº da fatura')),
                ('data_fatura', models.DateField(verbose_name='data da fatura')),
                ('data_vencimento', models.DateField(verbose_name='vencimento')),
                ('arquivo_fatura', models.FileField(blank=True, null=True, upload_to='compras/faturas/')),
                ('is_paga', models.BooleanField(default=False)),
                ('despesa_vinculada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.despesa')),
                ('ordem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fatura', to='compras.ordemcompra')),
            ],
            options={
                'verbose_name': 'fatura de compra',
            },
        ),
        migrations.CreateModel(
            name='RececaoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_rececao', models.DateTimeField(auto_now_add=True)),
                ('documento_guia', models.FileField(blank=True, null=True, upload_to='compras/guias/')),
                ('notas', models.TextField(blank=True)),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rececoes', to='compras.ordemcompra')),
                ('recebido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'receção de stock',
                'verbose_name_plural': 'receções de stock',
            },
        ),
    ]
