# Generated by Django 6.0.1 on 2026-01-08 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmacias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('icone', models.CharField(blank=True, help_text='Nome do ícone (ex: pill, syringe)', max_length=50, verbose_name='ícone')),
                ('is_ativa', models.BooleanField(default=True, verbose_name='ativa')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'categoria de produto',
                'verbose_name_plural': 'categorias de produtos',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='EstoqueProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=0, verbose_name='quantidade')),
                ('quantidade_minima', models.PositiveIntegerField(default=10, verbose_name='quantidade mínima')),
                ('lote', models.CharField(blank=True, max_length=50, verbose_name='lote')),
                ('data_fabricacao', models.DateField(blank=True, null=True, verbose_name='data de fabricação')),
                ('data_validade', models.DateField(blank=True, null=True, verbose_name='data de validade')),
                ('preco_custo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço de custo')),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço de venda')),
                ('preco_promocional', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='preço promocional')),
                ('em_promocao', models.BooleanField(default=False, verbose_name='em promoção')),
                ('localizacao_estoque', models.CharField(blank=True, help_text='Ex: Prateleira A, Setor 3', max_length=100, verbose_name='localização no estoque')),
                ('is_disponivel', models.BooleanField(default=True, verbose_name='disponível')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='data de atualização')),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='farmacias.farmacia', verbose_name='farmácia')),
            ],
            options={
                'verbose_name': 'estoque de produto',
                'verbose_name_plural': 'estoques de produtos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('AJUSTE', 'Ajuste'), ('DEVOLUCAO', 'Devolução'), ('PERDA', 'Perda')], max_length=20, verbose_name='tipo')),
                ('quantidade', models.IntegerField(verbose_name='quantidade')),
                ('quantidade_anterior', models.PositiveIntegerField(verbose_name='quantidade anterior')),
                ('quantidade_nova', models.PositiveIntegerField(verbose_name='quantidade nova')),
                ('motivo', models.TextField(blank=True, verbose_name='motivo')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True, verbose_name='data de movimentação')),
                ('estoque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='produtos.estoqueproduto', verbose_name='estoque')),
            ],
            options={
                'verbose_name': 'movimentação de estoque',
                'verbose_name_plural': 'movimentações de estoque',
                'ordering': ['-data_movimentacao'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('nome_generico', models.CharField(blank=True, max_length=200, verbose_name='nome genérico')),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='código de barras')),
                ('codigo_interno', models.CharField(blank=True, max_length=50, verbose_name='código interno')),
                ('tipo', models.CharField(choices=[('MEDICAMENTO', 'Medicamento'), ('SUPLEMENTO', 'Suplemento'), ('COSMETICO', 'Cosmético'), ('HIGIENE', 'Higiene'), ('EQUIPAMENTO', 'Equipamento'), ('OUTRO', 'Outro')], default='MEDICAMENTO', max_length=20, verbose_name='tipo')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('composicao', models.TextField(blank=True, verbose_name='composição')),
                ('indicacao', models.TextField(blank=True, verbose_name='indicação')),
                ('contraindicacao', models.TextField(blank=True, verbose_name='contraindicação')),
                ('posologia', models.TextField(blank=True, verbose_name='posologia')),
                ('fabricante', models.CharField(blank=True, max_length=200, verbose_name='fabricante')),
                ('pais_origem', models.CharField(blank=True, max_length=100, verbose_name='país de origem')),
                ('requer_receita', models.BooleanField(default=False, verbose_name='requer receita')),
                ('controlado', models.BooleanField(default=False, verbose_name='controlado')),
                ('registro_ministerio', models.CharField(blank=True, max_length=100, verbose_name='registro ministério')),
                ('forma_farmaceutica', models.CharField(blank=True, help_text='Ex: comprimido, cápsula, xarope, pomada', max_length=100, verbose_name='forma farmacêutica')),
                ('concentracao', models.CharField(blank=True, max_length=100, verbose_name='concentração')),
                ('quantidade_embalagem', models.CharField(blank=True, max_length=100, verbose_name='quantidade por embalagem')),
                ('imagem_principal', models.ImageField(blank=True, null=True, upload_to='produtos/', verbose_name='imagem principal')),
                ('is_ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='data de atualização')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='produtos.categoriaproduto', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='estoqueproduto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='produtos.produto', verbose_name='produto'),
        ),
        migrations.AlterUniqueTogether(
            name='estoqueproduto',
            unique_together={('farmacia', 'produto', 'lote')},
        ),
    ]
