# Generated by Django 5.2.10 on 2026-01-25 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='custo_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='custo unitário'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='preco_venda_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='preço venda unitário'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='referencia_externa',
            field=models.CharField(blank=True, help_text='Ex: Pedido #123, Nota Fiscal #456', max_length=100, verbose_name='referência externa'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_estoque', to=settings.AUTH_USER_MODEL, verbose_name='usuário responsável'),
        ),
    ]
