# Generated by Django 5.2.10 on 2026-01-25 10:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacias', '0003_farmacia_banco_conta_farmacia_banco_nib_and_more'),
        ('fornecedores', '0001_initial'),
        ('produtos', '0002_movimentacaoestoque_custo_unitario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_nota', models.CharField(max_length=100, verbose_name='número da nota/fatura')),
                ('data_emissao', models.DateField(blank=True, null=True, verbose_name='data de emissão')),
                ('data_entrada', models.DateField(default=django.utils.timezone.now, verbose_name='data de entrada')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='valor total')),
                ('arquivo_nota', models.FileField(blank=True, null=True, upload_to='notas_fiscais/', verbose_name='arquivo nota fiscal')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('processada', models.BooleanField(default=False, verbose_name='estoque processado')),
                ('financeiro_gerado', models.BooleanField(default=False, verbose_name='financeiro gerado')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_criadas', to=settings.AUTH_USER_MODEL)),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas_estoque', to='farmacias.farmacia', verbose_name='farmácia')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='fornecedores.fornecedor', verbose_name='fornecedor')),
            ],
            options={
                'verbose_name': 'entrada de estoque',
                'verbose_name_plural': 'entradas de estoque',
                'ordering': ['-data_entrada'],
            },
        ),
        migrations.CreateModel(
            name='ItemEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='quantidade')),
                ('preco_custo_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='custo unitário')),
                ('lote', models.CharField(max_length=50, verbose_name='lote')),
                ('data_validade', models.DateField(blank=True, null=True, verbose_name='data de validade')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='produtos.entradaestoque')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produto', verbose_name='produto')),
            ],
        ),
    ]
