# Generated by Django 5.2.10 on 2026-01-29 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacias', '0004_farmacia_percentual_iva'),
        ('produtos', '0003_entradaestoque_itementrada'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='estoqueproduto',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='estoqueproduto',
            name='local',
            field=models.CharField(choices=[('LOJA', 'Loja'), ('ARMAZEM', 'Armazém'), ('OUTRO', 'Outro')], default='LOJA', max_length=10, verbose_name='local de armazenamento'),
        ),
        migrations.AddField(
            model_name='estoqueproduto',
            name='preco_venda_avulso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='preço de venda avulso'),
        ),
        migrations.AddField(
            model_name='produto',
            name='is_isento_iva',
            field=models.BooleanField(default=False, verbose_name='isento de IVA'),
        ),
        migrations.AddField(
            model_name='produto',
            name='permite_venda_avulsa',
            field=models.BooleanField(default=False, help_text='Ex: vender 1 comprimido de uma cartela', verbose_name='permite venda avulsa'),
        ),
        migrations.AddField(
            model_name='produto',
            name='taxa_iva',
            field=models.DecimalField(decimal_places=2, default=16.0, max_digits=5, verbose_name='taxa de IVA (%)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='unidade_medida',
            field=models.CharField(choices=[('UNIDADE', 'Unidade'), ('CAIXA', 'Caixa'), ('FRASCO', 'Frasco'), ('CARTELA', 'Cartela/Blister'), ('ML', 'Mililitros'), ('G', 'Gramas')], default='UNIDADE', max_length=20, verbose_name='unidade de medida'),
        ),
        migrations.AddField(
            model_name='produto',
            name='unidades_por_caixa',
            field=models.PositiveIntegerField(default=1, help_text='Quantidade de unidades individuais dentro de uma caixa/embalagem', verbose_name='unidades por caixa/embalagem'),
        ),
        migrations.AlterUniqueTogether(
            name='estoqueproduto',
            unique_together={('farmacia', 'produto', 'lote', 'local')},
        ),
    ]
