# Generated by Django 5.2.10 on 2026-01-29 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_alter_estoqueproduto_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('AJUSTE', 'Ajuste'), ('DEVOLUCAO', 'Devolução'), ('PERDA', 'Perda'), ('TRANSFERENCIA', 'Transferência')], max_length=20, verbose_name='tipo'),
        ),
    ]
