# Generated by Django 5.2.10 on 2026-01-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_alter_movimentacaoestoque_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='percentual_comissao',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Comissão paga ao vendedor por cada unidade vendida', max_digits=5, verbose_name='percentual de comissão (%)'),
        ),
    ]
