# Generated by Django 5.2.10 on 2026-01-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_produto_percentual_comissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='itementrada',
            name='tipo_unidade',
            field=models.CharField(choices=[('CAIXA', 'Caixa/Embalagem'), ('UNIDADE', 'Unidade/Carteira')], default='CAIXA', max_length=10, verbose_name='tipo de unidade'),
        ),
    ]
