# Generated by Django 5.2.10 on 2026-02-22 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmacias', '0007_farmacia_meta_bonus_mensal_and_more'),
        ('financeiro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Caixa 01, Balcão Principal', max_length=100, verbose_name='nome do caixa')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='código')),
                ('is_ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caixas', to='farmacias.farmacia')),
            ],
            options={
                'verbose_name': 'caixa',
                'verbose_name_plural': 'caixas',
                'unique_together': {('farmacia', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='SessaoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_abertura', models.DateTimeField(auto_now_add=True, verbose_name='data de abertura')),
                ('data_fechamento', models.DateTimeField(blank=True, null=True, verbose_name='data de fechamento')),
                ('valor_abertura', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='valor de abertura')),
                ('valor_declarado_dinheiro', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='dinheiro declarado')),
                ('valor_declarado_pos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='cartão/POS declarado')),
                ('valor_declarado_mpesa', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='M-Pesa declarado')),
                ('valor_declarado_emola', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='e-Mola declarado')),
                ('valor_declarado_outros', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='outros declarado')),
                ('valor_sistema_dinheiro', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='dinheiro sistema')),
                ('valor_sistema_pos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='cartão/POS sistema')),
                ('valor_sistema_mpesa', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='M-Pesa sistema')),
                ('valor_sistema_emola', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='e-Mola sistema')),
                ('valor_sistema_outros', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='outros sistema')),
                ('total_declarado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='total declarado')),
                ('total_sistema', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='total sistema')),
                ('diferenca', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='diferença/quebra')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado'), ('CONCILIADO', 'Conciliado pelo Gestor')], default='ABERTO', max_length=20)),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('comprovante_fecho', models.ImageField(blank=True, null=True, upload_to='caixas/fechos/', verbose_name='comprovante de fecho')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes', to='caixa.caixa')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes_caixa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sessão de caixa',
                'verbose_name_plural': 'sessões de caixa',
                'ordering': ['-data_abertura'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('REFORCO', 'Reforço (Entrada de Trocos)'), ('SANGRIA', 'Sangria (Retirada de Dinheiro)'), ('PAGAMENTO', 'Pagamento de Despesa no Caixa')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('motivo', models.CharField(max_length=255)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('despesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.despesa')),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos', to='caixa.sessaocaixa')),
            ],
            options={
                'verbose_name': 'movimento de caixa',
                'verbose_name_plural': 'movimentos de caixa',
                'ordering': ['-data_hora'],
            },
        ),
    ]
